import { Component, computed, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { NavigationService } from '../../../core/services/navigation.service';
import { PermissionService } from '../../../core/services/permission.service';
interface SidebarItem{label:string;route:string;visible:boolean}
@Component({selector:'app-sidebar',imports:[RouterLink,RouterLinkActive],templateUrl:'./sidebar.html',styleUrl:'./sidebar.css'})
export class SidebarComponent{protected readonly navigation=inject(NavigationService);private readonly auth=inject(AuthService);private readonly permissions=inject(PermissionService);readonly items=computed<SidebarItem[]>(()=>{const owner=String(this.auth.user()?.user_metadata['role']??'').toUpperCase()==='OWNER';return[
{label:'Dashboard',route:'/app',visible:true},{label:'POS',route:'/app/pos',visible:this.permissions.hasPermission('sales.create')},{label:'Ventas',route:'/app/ventas',visible:this.permissions.hasPermission('sales.read')},{label:'Productos',route:'/app/productos',visible:this.permissions.hasPermission('products.read')},{label:'Categorías',route:'/app/categorias',visible:owner},{label:'Marcas',route:'/app/marcas',visible:owner},{label:'Talles',route:'/app/talles',visible:owner},{label:'Colores',route:'/app/colores',visible:owner},{label:'Inventario',route:'/app/inventario',visible:this.permissions.hasPermission('stock.read')},{label:'Operaciones',route:'/app/operaciones',visible:owner},{label:'Etiquetas',route:'/app/etiquetas',visible:owner},{label:'Compras',route:'/app/compras',visible:owner},{label:'Clientes',route:'/app/clientes',visible:true},{label:'Proveedores',route:'/app/proveedores',visible:owner},{label:'Dueños',route:'/app/duenos',visible:owner},{label:'Caja',route:'/app/caja',visible:true},{label:'Devoluciones',route:'/app/devoluciones',visible:this.permissions.hasPermission('returns.create')},{label:'Cambios',route:'/app/cambios',visible:this.permissions.hasPermission('exchanges.create')},{label:'Reportes',route:'/app/reportes',visible:owner},{label:'Usuarios',route:'/app/usuarios',visible:owner},{label:'Configuración',route:'/app/configuracion',visible:owner},{label:'Auditoría',route:'/app/auditoria',visible:owner}].filter(i=>i.visible)});closeMobileSidebar(){this.navigation.closeSidebar();}}
