begin;
create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['businesses','owners','profiles','categories','brands','sizes','colors','suppliers','products','product_variants','customers','purchases','sales'] loop execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()',t||'_touch',t); end loop; end $$;

create or replace function public.open_cash_register(p_register_id uuid,p_opening numeric) returns uuid language plpgsql security definer set search_path=public as $$
declare v_profile uuid:=public.current_profile_id(); v_business uuid:=public.current_business_id(); v_id uuid;
begin if v_profile is null or p_opening<0 then raise exception 'Datos de apertura inválidos'; end if;
insert into cash_sessions(business_id,cash_register_id,opened_by,opening_amount) select v_business,id,v_profile,p_opening from cash_registers where id=p_register_id and business_id=v_business and active returning id into v_id;
if v_id is null then raise exception 'Caja inexistente'; end if;
insert into cash_movements(business_id,cash_session_id,movement_type,amount,description,performed_by) values(v_business,v_id,'OPENING',p_opening,'Apertura de caja',v_profile); return v_id; end $$;

create or replace function public.confirm_purchase(p_purchase_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare v_p purchases%rowtype; v_i purchase_items%rowtype; v_lot uuid; v_prev int;
begin if public.current_role()<>'OWNER' then raise exception 'Permiso denegado'; end if;
select * into v_p from purchases where id=p_purchase_id and business_id=public.current_business_id() and status='DRAFT' for update;
if not found then raise exception 'Compra no disponible'; end if;
for v_i in select * from purchase_items where purchase_id=v_p.id loop
 insert into inventory_lots(business_id,variant_id,owner_id,purchase_item_id,unit_cost,initial_quantity,available_quantity,received_at) values(v_p.business_id,v_i.variant_id,v_p.owner_id,v_i.id,v_i.unit_cost,v_i.quantity,v_i.quantity,v_p.purchased_at) returning id into v_lot;
 insert into inventory_balances(business_id,variant_id,owner_id,quantity) values(v_p.business_id,v_i.variant_id,v_p.owner_id,v_i.quantity) on conflict(business_id,variant_id,owner_id) do update set quantity=inventory_balances.quantity+excluded.quantity,updated_at=now() returning quantity-v_i.quantity into v_prev;
 insert into stock_movements(business_id,variant_id,owner_id,lot_id,quantity,movement_type,previous_stock,resulting_stock,performed_by,reference_id,reference_type) values(v_p.business_id,v_i.variant_id,v_p.owner_id,v_lot,v_i.quantity,'PURCHASE_ENTRY',v_prev,v_prev+v_i.quantity,public.current_profile_id(),v_p.id,'PURCHASE');
end loop; update purchases set status='CONFIRMED' where id=v_p.id;
insert into audit_logs(business_id,actor_profile_id,action,entity_type,entity_id,new_data) values(v_p.business_id,public.current_profile_id(),'CONFIRM','PURCHASE',v_p.id,to_jsonb(v_p)); end $$;

create or replace function public.complete_sale(p_cash_session uuid,p_customer uuid,p_items jsonb,p_payments jsonb,p_discount numeric default 0) returns uuid language plpgsql security definer set search_path=public as $$
declare v_business uuid:=public.current_business_id(); v_profile uuid:=public.current_profile_id(); v_sale uuid; v_item jsonb; v_payment jsonb; v_si uuid; v_lot inventory_lots%rowtype; v_qty int; v_total numeric:=0; v_sub numeric; v_paid numeric; v_prev int;
begin if v_profile is null or not public.has_permission('sales.create') then raise exception 'Permiso denegado'; end if;
if not exists(select 1 from cash_sessions where id=p_cash_session and business_id=v_business and status='OPEN' and (opened_by=v_profile or public.current_role()='OWNER')) then raise exception 'Caja cerrada o inválida'; end if;
for v_item in select * from jsonb_array_elements(p_items) loop v_total:=v_total+((v_item->>'quantity')::int*(v_item->>'unit_price')::numeric-coalesce((v_item->>'discount')::numeric,0)); end loop;
v_total:=v_total-coalesce(p_discount,0); select coalesce(sum((x->>'amount')::numeric),0) into v_paid from jsonb_array_elements(p_payments) x; if v_total<0 or v_paid<>v_total then raise exception 'Los pagos no coinciden con el total'; end if;
insert into sales(business_id,cashier_id,customer_id,cash_session_id,subtotal,discount,total) values(v_business,v_profile,p_customer,p_cash_session,v_total+coalesce(p_discount,0),coalesce(p_discount,0),v_total) returning id into v_sale;
for v_item in select * from jsonb_array_elements(p_items) loop v_qty:=(v_item->>'quantity')::int; v_sub:=v_qty*(v_item->>'unit_price')::numeric-coalesce((v_item->>'discount')::numeric,0); insert into sale_items(sale_id,variant_id,quantity,unit_price,discount,subtotal) values(v_sale,(v_item->>'variant_id')::uuid,v_qty,(v_item->>'unit_price')::numeric,coalesce((v_item->>'discount')::numeric,0),v_sub) returning id into v_si;
 for v_lot in select * from inventory_lots where business_id=v_business and variant_id=(v_item->>'variant_id')::uuid and owner_id=(v_item->>'owner_id')::uuid and available_quantity>0 order by received_at,id for update loop exit when v_qty=0; v_prev:=least(v_qty,v_lot.available_quantity); update inventory_lots set available_quantity=available_quantity-v_prev where id=v_lot.id; insert into sale_item_allocations(sale_item_id,owner_id,lot_id,quantity,unit_cost) values(v_si,v_lot.owner_id,v_lot.id,v_prev,v_lot.unit_cost); v_qty:=v_qty-v_prev; end loop;
 if v_qty>0 then raise exception 'Stock insuficiente'; end if; select quantity into v_prev from inventory_balances where business_id=v_business and variant_id=(v_item->>'variant_id')::uuid and owner_id=(v_item->>'owner_id')::uuid for update; update inventory_balances set quantity=quantity-(v_item->>'quantity')::int,updated_at=now() where business_id=v_business and variant_id=(v_item->>'variant_id')::uuid and owner_id=(v_item->>'owner_id')::uuid; insert into stock_movements(business_id,variant_id,owner_id,quantity,movement_type,previous_stock,resulting_stock,performed_by,reference_id,reference_type) values(v_business,(v_item->>'variant_id')::uuid,(v_item->>'owner_id')::uuid,-(v_item->>'quantity')::int,'SALE',v_prev,v_prev-(v_item->>'quantity')::int,v_profile,v_sale,'SALE'); end loop;
for v_payment in select * from jsonb_array_elements(p_payments) loop insert into sale_payments(sale_id,payment_method_id,amount,external_reference) values(v_sale,(v_payment->>'payment_method_id')::uuid,(v_payment->>'amount')::numeric,v_payment->>'reference'); insert into cash_movements(business_id,cash_session_id,movement_type,amount,payment_method_id,reference_id,description,performed_by) values(v_business,p_cash_session,'SALE',(v_payment->>'amount')::numeric,(v_payment->>'payment_method_id')::uuid,v_sale,'Venta',v_profile); end loop;
insert into audit_logs(business_id,actor_profile_id,action,entity_type,entity_id) values(v_business,v_profile,'CREATE','SALE',v_sale); return v_sale; end $$;

create or replace function public.close_cash_register(p_session uuid,p_counted numeric,p_notes text default null) returns void language plpgsql security definer set search_path=public as $$ declare v_expected numeric; begin if p_counted<0 then raise exception 'Monto inválido'; end if; select opening_amount+coalesce((select sum(case when movement_type='OPENING' then 0 else amount end) from cash_movements where cash_session_id=p_session),0) into v_expected from cash_sessions where id=p_session and business_id=public.current_business_id() and status='OPEN' for update; if not found then raise exception 'Caja inválida'; end if; update cash_sessions set status='CLOSED',closed_by=public.current_profile_id(),expected_amount=v_expected,counted_amount=p_counted,difference=p_counted-v_expected,closed_at=now(),notes=p_notes where id=p_session; end $$;

revoke all on function public.open_cash_register(uuid,numeric),public.confirm_purchase(uuid),public.complete_sale(uuid,uuid,jsonb,jsonb,numeric),public.close_cash_register(uuid,numeric,text) from public;
grant execute on function public.open_cash_register(uuid,numeric),public.confirm_purchase(uuid),public.complete_sale(uuid,uuid,jsonb,jsonb,numeric),public.close_cash_register(uuid,numeric,text) to authenticated;
commit;
