import { DatePipe, DecimalPipe } from '@angular/common';
import { Component, HostListener, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CartItem, InventoryRow, SalePaymentInput } from '../../../../core/models/domain.model';
import { BusinessContextService } from '../../../../core/services/business-context.service';
import { CashService } from '../../../../core/services/cash.service';
import { DataAccessService } from '../../../../core/services/data-access.service';
import { InventoryService } from '../../../../core/services/inventory.service';
import { PermissionService } from '../../../../core/services/permission.service';
import { SaleService } from '../../../../core/services/sale.service';
import { SupabaseService } from '../../../../core/services/supabase.service';
import { ToastService } from '../../../../core/services/toast.service';

interface PaymentMethod { id:string; name:string; code:string; active:boolean }
interface Customer { id:string; first_name:string; last_name?:string }
interface Receipt { id:string; saleNumber:number; total:number; createdAt:Date; items:CartItem[]; payments:SalePaymentInput[]; customerName:string; cashierName:string }

@Component({selector:'app-pos-page',imports:[FormsModule,DecimalPipe,DatePipe],templateUrl:'./pos-page.html',styleUrl:'./pos-page.css'})
export class PosPageComponent implements OnInit {
  private readonly inventory=inject(InventoryService);private readonly sales=inject(SaleService);private readonly cash=inject(CashService);private readonly data=inject(DataAccessService);private readonly client=inject(SupabaseService).client;private readonly toast=inject(ToastService);private readonly permissions=inject(PermissionService);private readonly business=inject(BusinessContextService);
  readonly stock=signal<InventoryRow[]>([]);readonly cart=signal<CartItem[]>([]);readonly methods=signal<PaymentMethod[]>([]);readonly customers=signal<Customer[]>([]);readonly payments=signal<SalePaymentInput[]>([]);readonly cashSession=signal<any>(null);readonly loading=signal(false);readonly completedSale=signal<Receipt|null>(null);readonly ticketWidth=signal(80);
  readonly canAdjustPrices=computed(()=>this.permissions.hasRole('OWNER'));readonly storeName=computed(()=>this.business.activeBusiness()?.name??'VESTIA');readonly storeLogo=computed(()=>this.business.activeBusiness()?.logoUrl??null);readonly storeAddress=computed(()=>this.business.activeBusiness()?.address??'');readonly storePhone=computed(()=>this.business.activeBusiness()?.phone??'');
  search='';customerId='';generalDiscount=0;selectedMethod='';paymentAmount=0;
  readonly subtotal=computed(()=>this.cart().reduce((sum,item)=>sum+item.quantity*item.unitPrice-item.discount,0));readonly total=computed(()=>Math.max(0,this.subtotal()-Number(this.generalDiscount||0)));readonly paid=computed(()=>this.payments().reduce((sum,payment)=>sum+payment.amount,0));readonly pending=computed(()=>Number((this.total()-this.paid()).toFixed(2)));

  async ngOnInit(){await Promise.all([this.refresh(),this.loadTicketSettings()]);}
  private async loadTicketSettings(){const{data}=await this.client.from('app_settings').select('ticket_settings').maybeSingle();const settings=data?.ticket_settings as{width?:number}|null;if(settings?.width===58||settings?.width===80)this.ticketWidth.set(settings.width);}
  async refresh(){this.loading.set(true);try{const[stock,methods,session,customers]=await Promise.all([this.inventory.list(this.search),this.data.list<PaymentMethod>('payment_methods',{pageSize:50,active:true}),this.cash.current(),this.data.list<Customer>('customers',{pageSize:200,active:true})]);this.stock.set(stock);this.methods.set(methods.items.filter(method=>method.code!=='EXCHANGE_CREDIT'));this.customers.set(customers.items);this.cashSession.set(session);if(!this.selectedMethod&&this.methods().length)this.selectedMethod=this.methods()[0].id;const term=this.search.trim().toLowerCase(),exact=stock.filter(row=>row.barcode.toLowerCase()===term||row.sku.toLowerCase()===term);if(term&&exact.length===1){this.add(exact[0]);this.search='';setTimeout(()=>document.querySelector<HTMLInputElement>('#pos-search')?.focus());}}catch(error){this.fail(error);}finally{this.loading.set(false);}}
  add(row:InventoryRow){if(row.quantity<=0)return;const current=this.cart().find(item=>item.variantId===row.variantId&&item.ownerId===row.ownerId);if(current){if(current.quantity>=current.available){this.toast.show({title:'Stock insuficiente',description:`Disponible: ${current.available}`,variant:'warning'});return;}this.cart.update(items=>items.map(item=>item===current?{...item,quantity:item.quantity+1}:item));}else this.cart.update(items=>[...items,{variantId:row.variantId,ownerId:row.ownerId,productName:row.productName,variantName:`${row.color??'—'} / ${row.size??'—'}`,sku:row.sku,quantity:1,available:row.quantity,unitPrice:row.price,discount:0}]);}
  quantity(item:CartItem,delta:number){this.cart.update(items=>items.map(current=>current===item?{...current,quantity:Math.max(1,Math.min(current.available,current.quantity+delta))}:current));}
  price(item:CartItem,value:unknown){if(!this.canAdjustPrices())return;this.cart.update(items=>items.map(current=>current===item?{...current,unitPrice:Number(value)||0}:current));}
  remove(item:CartItem){this.cart.update(items=>items.filter(current=>current!==item));}
  addPayment(){const amount=Number(this.paymentAmount||this.pending());if(!this.selectedMethod||amount<=0||amount>this.pending()){this.toast.show({title:'Importe de pago inválido',variant:'warning'});return;}this.payments.update(payments=>[...payments,{paymentMethodId:this.selectedMethod,amount}]);this.paymentAmount=0;}
  removePayment(index:number){this.payments.update(payments=>payments.filter((_,current)=>current!==index));}methodName(id:string){return this.methods().find(method=>method.id===id)?.name??'Pago';}
  async charge(){if(!this.cashSession()){this.toast.show({title:'Abrí una caja antes de cobrar',variant:'warning'});return;}if(!this.cart().length||this.cart().some(item=>item.unitPrice<=0)){this.toast.show({title:'Carrito incompleto',variant:'warning'});return;}if(!this.payments().length&&this.selectedMethod)this.payments.set([{paymentMethodId:this.selectedMethod,amount:this.total()}]);if(Math.abs(this.pending())>.001){this.toast.show({title:'La suma de pagos debe coincidir con el total',description:`Pendiente: $ ${this.pending()}`,variant:'warning'});return;}this.loading.set(true);try{const receiptItems=this.cart().map(item=>({...item})),receiptPayments=this.payments().map(payment=>({...payment})),receiptTotal=this.total();const id=await this.sales.complete({cashSessionId:this.cashSession().id,customerId:this.customerId||null,discount:Number(this.generalDiscount)||0,items:this.cart(),payments:this.payments()});const detail=await this.sales.detail(id),customer=this.customers().find(item=>item.id===this.customerId);this.completedSale.set({id,saleNumber:detail.sale_number,total:receiptTotal,createdAt:new Date(detail.created_at),items:receiptItems,payments:receiptPayments,customerName:customer?`${customer.first_name} ${customer.last_name??''}`.trim():'Consumidor final',cashierName:`${detail.profiles.first_name} ${detail.profiles.last_name}`.trim()});this.cart.set([]);this.toast.show({title:'Venta realizada correctamente',variant:'success'});await this.refresh();}catch(error){this.fail(error);}finally{this.loading.set(false);}}
  newSale(){this.completedSale.set(null);this.generalDiscount=0;this.paymentAmount=0;this.payments.set([]);this.customerId='';}print(){window.print();}
  @HostListener('window:keydown',['$event'])shortcuts(event:KeyboardEvent){if(event.key==='F2'){event.preventDefault();this.newSale();}if(event.key==='F8'){event.preventDefault();void this.charge();}if(event.key==='F4'||(event.ctrlKey&&event.key.toLowerCase()==='k')){event.preventDefault();document.querySelector<HTMLInputElement>('#pos-search')?.focus();}}
  private fail(error:unknown){this.toast.show({title:'No se pudo completar la operación',description:error instanceof Error?error.message:'Verificá Supabase.',variant:'danger'});}
}
