begin;
create or replace function public.register_return(p_sale uuid,p_allocations jsonb,p_reason text,p_refund numeric default 0,p_cash_session uuid default null) returns uuid language plpgsql security definer set search_path=public as $$
declare v_business uuid:=public.current_business_id();v_profile uuid:=public.current_profile_id();v_return uuid;v_input jsonb;v_a sale_item_allocations%rowtype;v_si sale_items%rowtype;v_prev int;v_total_sold int;v_total_returned int;
begin if public.current_role()<>'OWNER' and not public.has_permission('returns.create') then raise exception 'Permiso denegado';end if;if p_refund<0 then raise exception 'Reintegro inválido';end if;if not exists(select 1 from sales where id=p_sale and business_id=v_business and status in('COMPLETED','PARTIALLY_RETURNED')) then raise exception 'Venta no disponible';end if;
insert into returns(business_id,original_sale_id,cash_session_id,processed_by,reason,refund_amount)values(v_business,p_sale,p_cash_session,v_profile,p_reason,p_refund)returning id into v_return;
for v_input in select * from jsonb_array_elements(p_allocations)loop select * into v_a from sale_item_allocations where id=(v_input->>'allocation_id')::uuid for update;select * into v_si from sale_items where id=v_a.sale_item_id and sale_id=p_sale;if not found or (v_input->>'quantity')::int<=0 or (v_input->>'quantity')::int>v_a.quantity-coalesce((select sum(ri.quantity) from return_items ri join returns r on r.id=ri.return_id where ri.sale_item_allocation_id=v_a.id),0) then raise exception 'Cantidad de devolución inválida';end if;
insert into return_items(return_id,sale_item_allocation_id,quantity,condition)values(v_return,v_a.id,(v_input->>'quantity')::int,v_input->>'condition');update inventory_lots set available_quantity=available_quantity+(v_input->>'quantity')::int where id=v_a.lot_id returning available_quantity-(v_input->>'quantity')::int into v_prev;select quantity into v_prev from inventory_balances where business_id=v_business and variant_id=v_si.variant_id and owner_id=v_a.owner_id for update;update inventory_balances set quantity=quantity+(v_input->>'quantity')::int,updated_at=now()where business_id=v_business and variant_id=v_si.variant_id and owner_id=v_a.owner_id;insert into stock_movements(business_id,variant_id,owner_id,lot_id,quantity,movement_type,previous_stock,resulting_stock,performed_by,reference_id,reference_type,notes)values(v_business,v_si.variant_id,v_a.owner_id,v_a.lot_id,(v_input->>'quantity')::int,'RETURN',v_prev,v_prev+(v_input->>'quantity')::int,v_profile,v_return,'RETURN',p_reason);end loop;
if p_refund>0 then if p_cash_session is null then raise exception 'Se requiere caja para reintegrar';end if;insert into cash_movements(business_id,cash_session_id,movement_type,amount,reference_id,description,performed_by)values(v_business,p_cash_session,'REFUND',-p_refund,v_return,'Devolución',v_profile);end if;
select sum(si.quantity),coalesce(sum(ri.quantity),0) into v_total_sold,v_total_returned from sale_items si left join sale_item_allocations a on a.sale_item_id=si.id left join return_items ri on ri.sale_item_allocation_id=a.id where si.sale_id=p_sale;update sales set status=case when v_total_returned>=v_total_sold then 'RETURNED'::sale_status else 'PARTIALLY_RETURNED'::sale_status end where id=p_sale;insert into audit_logs(business_id,actor_profile_id,action,entity_type,entity_id,metadata)values(v_business,v_profile,'CREATE','RETURN',v_return,jsonb_build_object('sale_id',p_sale));return v_return;end $$;

create or replace view public.owner_sales_summary with(security_invoker=true)as select s.business_id,a.owner_id,o.first_name owner_first_name,o.last_name owner_last_name,date_trunc('day',s.created_at) sale_day,sum(a.quantity*si.unit_price)gross_sales,sum(a.quantity*a.unit_cost)cost,sum(a.quantity*(si.unit_price-a.unit_cost))estimated_profit,sum(a.quantity)units from sales s join sale_items si on si.sale_id=s.id join sale_item_allocations a on a.sale_item_id=si.id join owners o on o.id=a.owner_id where s.status<>'CANCELLED' group by s.business_id,a.owner_id,o.first_name,o.last_name,date_trunc('day',s.created_at);
create or replace view public.dashboard_summary with(security_invoker=true)as select b.id business_id,coalesce((select sum(total)from sales where business_id=b.id and created_at>=current_date and status<>'CANCELLED'),0)today_sales,coalesce((select sum(total)from sales where business_id=b.id and created_at>=date_trunc('month',now())and status<>'CANCELLED'),0)month_sales,coalesce((select sum(quantity)from inventory_balances where business_id=b.id),0)total_stock,coalesce((select count(*)from inventory_balances ib join product_variants v on v.id=ib.variant_id where ib.business_id=b.id and ib.quantity<=v.minimum_stock),0)low_stock from businesses b;
revoke all on function public.register_return(uuid,jsonb,text,numeric,uuid)from public;grant execute on function public.register_return(uuid,jsonb,text,numeric,uuid)to authenticated;
commit;
